FROM ubuntu:16.04

RUN mkdir -p /usr/src/app

# Install build tools
RUN apt-get update
RUN apt-get -y install wget patch build-essential libpcre3 libpcre3-dev
RUN apt-get -y install zlib1g-dev
RUN apt-get -y install libssl-dev

# Install testing tools
RUN apt-get -y install python python-setuptools python-pip net-tools

EXPOSE 80 443 3128

WORKDIR /usr/src/app
