FROM ubuntu:16.04

RUN mkdir -p /usr/src/app

# Install build tools
RUN apt-get update
RUN apt-get -y install wget patch build-essential libpcre3 libpcre3-dev gettext-base
RUN apt-get -y install zlib1g-dev
RUN apt-get -y install libssl-dev
RUN apt-get -y install faketime

# Install dnsmasq. Only required if not using proxy_connect_rewrite
# RUN apt-get -y install dnsmasq

# Install debugging tools
RUN apt-get -y install dnsutils curl vim tcptrack

EXPOSE 80 443 3128

WORKDIR /usr/src/app

COPY certs ./certs
COPY conf ./conf
COPY ngx_http_proxy_connect_module ./ngx_http_proxy_connect_module
COPY scripts ./scripts
COPY test ./test
COPY patches ./patches
COPY *.sh ./
COPY Makefile .

CMD ["make", "run"]
