version: "2"
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
      - "3128:3128"
    volumes:
      - ./data/logs:/usr/src/app/build/logs
      - ./data/content_cache:/data/funes/content_cache
    # command: ["bash", "-c", "sleep infinity"]
    environment:
      - VERBOSE=true
      - DISABLE_TRANSPARENT_PROXY=1
      - DISABLE_DYNAMIC_CERTS=1
      - ENABLE_ACCESS_LOGS=true
      - HOST=0.0.0.0
    # - PROXY_BUFFER_SIZE=128k
    # - PROXY_BUFFERS=4 128k
    # - PROXY_BUSY_BUFFERS_SIZE=128k
    # - DISABLE_RANGE_CACHE_EXPIRY_OVERRIDE=1
    # - PROXY_READ_DATA_TIMEOUT=600s
    # - PROXY_CONNECT_DATA_TIMEOUT=600s
